### ISSUE TITLE
Navbar do topo cria uma margem no topo quando blur esta ativado

### ISSUE THREAD

**Issue by murilopereirame** [murilopereirame/TP2-JS#1]
@ga-sr , quando o filtro blur está ativo, a navbar do topo cria uma margem. Tentei ativar o blur sem ser quando tem uma nova tarefa, e ocorre o mesmo  problema.

![image](https://user-images.githubusercontent.com/34790144/70087521-42ca1e80-15f3-11ea-9be0-1813e373c36f.png)

**Comment by ga-sr** [comment]
o problema é com o `position: fixed;` do .header
